### ISSUE TITLE
Pomocy

### ISSUE THREAD

**Issue by m3ku** [teapotd/eelbot#6]
Jak odpalić i czym tego bota?

**Comment by teapotd** [comment]
Masz instrukcje w README - https://github.com/teapotd/eelbot/blob/master/README.md
Jak to nie wystarcza to znaczy, że do niczego Ci się ten bot nie przyda :)

**Comment by m3ku** [comment]
jak dodać do botów łączenie z serwerem ponownie z tego samego nicku żeby omijały anty bot wiadomość i czy da się zrobić żeby boty wchodzily z nickami eelbot1,2,3 itd
