### ISSUE TITLE
Pingowanie serwera i nicki eelbot

### ISSUE THREAD

**Issue by m3ku** [teapotd/eelbot#7]
jak dodać do botów łączenie z serwerem ponownie z tego samego nicku żeby omijały anty bot wiadomość i czy da się zrobić żeby boty wchodzily z nickami eelbot1,2,3 itd

**Comment by teapotd** [comment]
> Minimalist "snake" bots for **testing** Minecraft servers.

Boty są przeznaczone do testowania wydajności własnego serwera, a nie innych serwerów bez zgody właściciela.

**Comment by m3ku** [comment]
tylko mi chodzi o to czy da się jakoś nimi obejść "wejdz ponownie na
serwer" jeżeli nie to dobrze to mam serwer zabezpieczony ;)

2017-09-13 4:25 GMT+02:00 teapotd <notifications@github.com>:
